### ISSUE TITLE
Documentation of operator customization

### ISSUE THREAD

**Issue by chaoming0625** [PKU-NIP-Lab/BrainPy#123]
Please:

- [x] Check for duplicate requests.
- [x] Describe your goal, and if possible provide a code snippet with a motivating example.

It's exiciting to see recet PR #122 which enables low-level operator customization in BrainPy just using numba. However, how do we use it? The documentation or the tutorial is still missing.

**Comment by ztqakita** [comment]
Yeah, it comes up to me that we need a tutorial for this new function. I am considering adding it to the advanced tutorials section.
