### ISSUE TITLE
Using the official example“Training a spiking neural network”, brainpy cannot call GPU acceleration

### ISSUE THREAD

**Issue by LinkYizhihh** [PKU-NIP-Lab/BrainPy#257]
CODE:
```
import brainpy as bp
import brainpy.math as bm

bm.set_platform('gpu')

E = bp.neurons.LIF(3200, V_rest=-60., V_th=-50., V_reset=-60.,
                   tau=20., tau_ref=5., method='exp_auto',
                   V_initializer=bp.init.Normal(-60., 2.))

I = bp.neurons.LIF(800, V_rest=-60., V_th=-50., V_reset=-60.,
                   tau=20., tau_ref=5., method='exp_auto',
                   V_initializer=bp.init.Normal(-60., 2.))

E2E = bp.synapses.Exponential(E, E, bp.conn.FixedProb(prob=0.02), g_max=0.6,
                              tau=5., output=bp.synouts.COBA(E=0.),
                              method='exp_auto')

E2I = bp.synapses.Exponential(E, I, bp.conn.FixedProb(prob=0.02), g_max=0.6,
                              tau=5., output=bp.synouts.COBA(E=0.),
                              method='exp_auto')

I2E = bp.synapses.Exponential(I, E, bp.conn.FixedProb(prob=0.02), g_max=6.7,
                              tau=10., output=bp.synouts.COBA(E=-80.),
                              method='exp_auto')

I2I = bp.synapses.Exponential(I, I, bp.conn.FixedProb(prob=0.02), g_max=6.7,
                              tau=10., output=bp.synouts.COBA(E=-80.),
                              method='exp_auto')

net = bp.dyn.Network(E2E, E2I, I2E, I2I, E=E, I=I)

runner = bp.dyn.DSRunner(net,
                         monitors=['E.spike', 'I.spike'],
                         inputs=[('E.input', 20.), ('I.input', 20.)],
                         dt=0.1)

runner.run(10000)
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 4.5))

plt.subplot(121)

bp.visualize.raster_plot(runner.mon.ts, runner.mon['E.spike'], show=False)
plt.subplot(122)
bp.visualize.raster_plot(runner.mon.ts, runner.mon['I.spike'], show=True)

```
ERROR
"""
Traceback (most recent call last):
  File "D:\SNN_MidBrain_Project\SNN_Sound source location\Midbrain_simulation_practice\brainpy\test2.py", line 37, in <module>
    runner.run(10000)
  File "C:\Users\Link\Anaconda3\lib\site-packages\brainpy\dyn\runners.py", line 500, in run
    return self.predict(*args, **kwargs)
  File "C:\Users\Link\Anaconda3\lib\site-packages\brainpy\dyn\runners.py", line 420, in predict
    outputs, hists = self._predict(xs=(times, indices, xs), shared_args=shared_args)
  File "C:\Users\Link\Anaconda3\lib\site-packages\brainpy\dyn\runners.py", line 464, in _predict
    outputs, hists = _predict_func(xs)
  File "C:\Users\Link\Anaconda3\lib\site-packages\brainpy\dyn\runners.py", line 590, in <lambda>
    run_func = lambda all_inputs: f(all_inputs)[1]
  File "C:\Users\Link\Anaconda3\lib\site-packages\brainpy\math\controls.py", line 167, in call
    dyn_values, (out_values, results) = lax.scan(
  File "C:\Users\Link\Anaconda3\lib\site-packages\brainpylib\event_sum.py", line 109, in _event_sum_translation
    raise ValueError('Cannot find compiled gpu wheels.')
ValueError: Cannot find compiled gpu wheels.
"""

I have tested Jax. Can call GPU operation successfully. But brainpy can't succeed. Can the official send an example to test whether it successfully calls GPU acceleration? I really need this, otherwise it's too slow to use the CPU

**Comment by chaoming0625** [comment]
Dear @LinkYizhihh , the GPU operator of  `event_sum` used in E/I balanced network is not included in the ``brainpylib`` pypi releases. All pypi releases of ``brainpylib`` are CPU version operators. 

There are two ways to solve this issue. 

1. Clone brainpy repo, go into `extensions` directory, and compile GPU wheel by user self. Like, 
```bash

> git clone https://github.com/PKU-NIP-Lab/BrainPy
> cd BrainPy/extensions
> python setup_cuda.py bdist_wheel
> pip install dist/brainpylib-*.whl 

``` 

2. Change the computing way of Exponential synapse model. Take `E2E` connection as the example,
```python

>>> E2E = bp.synapses.Exponential(E, E, bp.conn.FixedProb(prob=0.02), g_max=0.6,
                              tau=5., output=bp.synouts.COBA(E=0.),
                              method='exp_auto', 
                              comp_method='dense')
```
By default, Exponential synapse model uses sparse connections and event-driven computation, which are implemented in ``brainpylib`` package. By setting `comp_method='dense'`, it will computes the results by using the traditional dense matrix operators. These ops well work with CUDA. 

I hope this message can help you. 


By the way, we may need detailed documentation on how to compile ``brainpylib`` on GPU. @ztqakita

**Comment by LinkYizhihh** [comment]
Dear&nbsp;Chaoming Wang:
&nbsp; &nbsp; Thank you very much for your answer. I have some problems in the actual operation. I hope to get your help.

&nbsp; &nbsp;
&nbsp; &nbsp; &nbsp;This is the specific situation of the folder in the problem. But I don't understand what this means. I hope you can help me.













------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PKU-NIP-Lab/BrainPy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月5日(星期一) 中午11:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PKU-NIP-Lab/BrainPy] Using the official example“Training a spiking neural network”, brainpy cannot call GPU acceleration (Issue #257)





 
Dear @LinkYizhihh , the GPU operator of  event_sum used in E/I balanced network is not included in the brainpylib pypi releases. All pypi releases of brainpylib are CPU version operators.
 
There are two ways to solve this issue.
  
Clone brainpy repo, go into extensions directory, and compile GPU wheel by user self. Like,
  &gt; git clone https://github.com/PKU-NIP-Lab/BrainPy &gt; cd BrainPy/extensions &gt; python setup_cuda.py bdist_wheel &gt; pip install dist/brainpylib-*.whl  
  
Change the computing way of Exponential synapse model. Take E2E connection as the example,
  &gt;&gt;&gt; E2E = bp.synapses.Exponential(E, E, bp.conn.FixedProb(prob=0.02), g_max=0.6,                               tau=5., output=bp.synouts.COBA(E=0.),                               method='exp_auto',                                comp_method='dense')
 
By default, Exponential synapse model uses sparse connections and event-driven computation, which are implemented in brainpylib package. By setting comp_method='dense', it will computes the results by using the traditional dense matrix operators. These ops well work with CUDA.
 
I hope this message can help you.
 
By the way, we may need detailed documentation on how to compile brainpylib on GPU. @ztqakita

**Comment by ztqakita** [comment]
I am sorry but we can't receive your folder. I am wondering if it is convenient for you to post your problem here just like your first issue.

**Comment by LinkYizhihh** [comment]
Sorry, this is the error I reported when using CMD command. I don't quite understand what this means. I hope you can help me

CMD
'''
(base) C:\WINDOWS\system32>cd C:\Users\Link\Desktop\BrainPy-master\extensions

(base) C:\Users\Link\Desktop\BrainPy-master\extensions>python setup_cuda.py bdist_wheel
running bdist_wheel
running build
running build_py
running egg_info
writing brainpylib.egg-info\PKG-INFO
writing dependency_links to brainpylib.egg-info\dependency_links.txt
writing requirements to brainpylib.egg-info\requires.txt
writing top-level names to brainpylib.egg-info\top_level.txt
reading manifest file 'brainpylib.egg-info\SOURCES.txt'
writing manifest file 'brainpylib.egg-info\SOURCES.txt'
running build_ext
install_dir C:\Users\Link\Desktop\BrainPy-master\extensions\build\lib.win-amd64-3.9
-DCMAKE_INSTALL_PREFIX=C:\Users\Link\Desktop\BrainPy-master\extensions\build\lib.win-amd64-3.9 -DCMAKE_PREFIX_PATH=C:\Users\Link\Anaconda3\lib\site-packages\pybind11\share\cmake
error: [WinError 2] 系统找不到指定的文件。
'''

**Comment by LinkYizhihh** [comment]
Sorry, this is the error I reported when using anaconda prompt command. I don't quite understand what this means. I hope you can help me

anaconda prompt
'''
(base) C:\WINDOWS\system32>cd C:\Users\Link\Desktop\BrainPy-master\extensions

(base) C:\Users\Link\Desktop\BrainPy-master\extensions>python setup_cuda.py bdist_wheel
running bdist_wheel
running build
running build_py
running egg_info
writing brainpylib.egg-info\PKG-INFO
writing dependency_links to brainpylib.egg-info\dependency_links.txt
writing requirements to brainpylib.egg-info\requires.txt
writing top-level names to brainpylib.egg-info\top_level.txt
reading manifest file 'brainpylib.egg-info\SOURCES.txt'
writing manifest file 'brainpylib.egg-info\SOURCES.txt'
running build_ext
install_dir C:\Users\Link\Desktop\BrainPy-master\extensions\build\lib.win-amd64-3.9
-DCMAKE_INSTALL_PREFIX=C:\Users\Link\Desktop\BrainPy-master\extensions\build\lib.win-amd64-3.9 -DCMAKE_PREFIX_PATH=C:\Users\Link\Anaconda3\lib\site-packages\pybind11\share\cmake
error: [WinError 2] 系统找不到指定的文件。
'''

**Comment by ztqakita** [comment]
Dear @LinkYizhihh, I recognize you are using Windows cmd to install the GPU-version wheel. The best way to use GPU under Windows platform is to use WSL2 (or WSL) as the running environment. For Windows 10+ system, you can use [Windows Subsystem for Linux (WSL)](https://docs.microsoft.com/en-us/windows/wsl/about). The installation guide can be found in [WSL Installation Guide for Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10).

**Comment by chaoming0625** [comment]
I recommend you to use [the second option](https://github.com/PKU-NIP-Lab/BrainPy/issues/257#issuecomment-1236517306). Just simply setting ``comp_method='dense'`` in each synapse model. 

For the compilation of GPU version operators. I  agree with @ztqakita that users should use WSL2 on windows.
