### ISSUE TITLE
How to Use Synaptic Weights

### ISSUE THREAD

**Issue by LinkYizhihh** [PKU-NIP-Lab/BrainPy#264]
Hello, I don't understand the synaptic weight in the official document. The code example only shows how to set the synaptic weight, which is not related to the actual network simulation. I don't know how to set the weight in the network.
I try to modify the official EI network. Only these sentences are added
"E2E.init_weights(weight=0.0, comp_method='dense')
E2I.init_ weights(weight=0.0, comp_method='dense')
I2E.init_ weights(weight=0.0, comp_method='dense')
I2I.init_ weights(weight=0.0, comp_method='dense')"。
The weight is 0, and the final result should be no spike, but the graph drawn by the result is the same as that without these codes. I hope you can give me an example of how to set synaptic weights in the network.

```python
import brainpy as bp
import brainpy.math as bm
bm.set_platform('cpu')
E = bp.neurons.LIF(3200, V_rest=-60., V_th=-50., V_reset=-60.,
                   tau=20., tau_ref=5., method='exp_auto',
                   V_initializer=bp.init.Normal(-60., 2.))
I = bp.neurons.LIF(800, V_rest=-60., V_th=-50., V_reset=-60.,
                   tau=20., tau_ref=5., method='exp_auto',
                   V_initializer=bp.init.Normal(-60., 2.))
E2E = bp.synapses.Exponential(E, E, bp.conn.FixedProb(prob=0.02), g_max=0.6,
                              tau=5., output=bp.synouts.COBA(E=0.),
                              method='exp_auto')
E2I = bp.synapses.Exponential(E, I, bp.conn.FixedProb(prob=0.02), g_max=0.6,
                              tau=5., output=bp.synouts.COBA(E=0.),
                              method='exp_auto')
I2E = bp.synapses.Exponential(I, E, bp.conn.FixedProb(prob=0.02), g_max=6.7,
                              tau=10., output=bp.synouts.COBA(E=-80.),
                              method='exp_auto')
I2I = bp.synapses.Exponential(I, I, bp.conn.FixedProb(prob=0.02), g_max=6.7,
                              tau=10., output=bp.synouts.COBA(E=-80.),
                              method='exp_auto')
# Want to try to change the weight to 0
E2E.init_weights(weight=0.0, comp_method='dense')
E2I.init_weights(weight=0.0, comp_method='dense')
I2E.init_weights(weight=0.0, comp_method='dense')
I2I.init_weights(weight=0.0, comp_method='dense')
net = bp.dyn.Network(E2E, E2I, I2E, I2I, E=E, I=I)
runner = bp.dyn.DSRunner(net,
                         monitors=['E.spike', 'I.spike'],
                         inputs=[('E.input', 20.), ('I.input', 20.)],
                         dt=0.1)
runner.run(100)

import matplotlib.pyplot as plt
plt.figure(figsize=(12, 4.5))
plt.subplot(121)
bp.visualize.raster_plot(runner.mon.ts, runner.mon['E.spike'], show=False)
plt.subplot(122)
bp.visualize.raster_plot(runner.mon.ts, runner.mon['I.spike'], show=True)
```

- [ ] If applicable, include full error messages/tracebacks.

**Comment by chaoming0625** [comment]
Hello, ``.init_weights()`` is an internal method to be used for weight initialization. It should not be exposed to users. 

Instead, if you want to change weight, please use ``g_max`` argument. Moreover, weight initialization in BrainPy models is very very flexible. I will show you several examples. 

For your purpose, you can set the scalar weight ``0.`` as:

```python

E2E = bp.synapses.Exponential(E, E, bp.conn.FixedProb(prob=0.02), 
                              g_max=0.,   # set weights here!!!!!
                              tau=5., output=bp.synouts.COBA(E=0.),
                              method='exp_auto')
```

After this setting, the network will also show spikes, this is because the background inputs are strong to trigger the neurons to spike. Removing the background inputs will silent the whole network. 

However, it you want to set the heterogenous weights, you can use:


```python

E2E = bp.synapses.Exponential(E, E, bp.conn.FixedProb(prob=0.02), 
                              g_max=bp.init.Uniform(0., 1.),  # set weights HERE!!!
                              tau=5., output=bp.synouts.COBA(E=0.),
                              method='exp_auto')
```

More details please see our document: https://brainpy.readthedocs.io/en/latest/tutorial_building/overview_of_dynamic_model.html#initializing-a-synapse-model

Please update this issue if you have more questions!

**Comment by ztqakita** [comment]
Since it has been two weeks without additional questions, we suppose this issue has been solved and we have decided to close it.
