### ISSUE TITLE
Build time too long for large scale network model on GPU

### ISSUE THREAD

**Issue by PPistalent** [PKU-NIP-Lab/BrainPy#36]
We have tested a EI-balance LIF network model, with 32768 neurons, prob=1% synapse connection. It took hours to build the model.
![image](https://user-images.githubusercontent.com/42830026/112266544-1f772700-8caf-11eb-9edb-ba39deb09895.png)

My env: Python3.8, GPU:TITAN RTX+CUDA 11.0

**Comment by chaoming0625** [comment]
@PPistalent Thanks for your report. We will improve this problem in the formal release of version 1.0

**Comment by chaoming0625** [comment]
@PPistalent Dear PPistalent, we have updated the Numba CUDA backend of BrainPy in version of 1.0.0 rc2. Here we test an E/I balance network (COBA) with the neuron number of 4000 * 15 = 60, 000.  The code can be obtained in [examples/numba_cuda/COBA.py](https://github.com/PKU-NIP-Lab/BrainPy/blob/master/examples/numba_cuda/COBA.py). 

In this version of BrainPy, we did not see the long building problem. And for the running speed, in my GTX 980m machine, I got the following results:

```bash

Compilation used 1.7283 s.
Start running ...
Run 10.0% used 4.200 s.
Run 20.0% used 8.376 s.
Run 30.0% used 12.546 s.
Run 40.0% used 16.720 s.
Run 50.0% used 20.894 s.
Run 60.0% used 25.140 s.
Run 70.0% used 29.419 s.
Run 80.0% used 33.600 s.
Run 90.0% used 37.769 s.
Run 100.0% used 41.946 s.
Simulation is done in 41.946 s.

Used time 43.70895028114319 s.

```
