### ISSUE TITLE
a bug when importing numba

### ISSUE THREAD

**Issue by jiumao2** [PKU-NIP-Lab/BrainPy#4]
npbrain\tools\functions.py
numba.core.dispatcher is not available to my numba package. So I changed it to numba.dispatcher and then it worked.

**Comment by chaoming0625** [comment]
Thank your report. This error is caused by the inconsistency between **numba ==0.50.x** and **numba == 0.40.x**. 

- In numba == 0.40.x, _numba.dispatcher_
- In numba == 0.50.x, _numba.core.dispatcher_

We will fix it as soon as possible.

**Comment by chaoming0625** [comment]
Closed. See commit of [Fix the bug of "numba dispatcher" import](https://github.com/PKU-NIP-Lab/BrainPy/commit/0fb1b57dc3206954cdcc241506fc188bf4851b13)
