### ISSUE TITLE
``resolution`` should be specified to certain parameters in bifurcation analysis

### ISSUE THREAD

**Issue by c-xy17** [PKU-NIP-Lab/BrainPy#94]
The tutorial should emphasize that it is recommended to set ``resolution`` specified to certain parameters in bifurcation analysis. If it is applied to all variables and parameters, the computation may be too large to accomplish.

**Comment by chaoming0625** [comment]
Agree with it!

**Comment by chaoming0625** [comment]
I think it is time to add some warnings or notes to the analysis documentation. Would you like to make this effort? @c-xy17

**Comment by c-xy17** [comment]
It has been solved. A warning was added to LowDimAnalyzer to warn users if they set 'resolutions' as a float number. The analysis tutorial was updated, too.
